name: 'Google Cloud SQL Proxy with workload identity'
description: 'Start Google CloudSQL Proxy using Google Workload Identity Federation short-lived credentials'

branding:
  icon: 'database'
  color: 'red'

inputs:
  creds:
    description: 'Contents of a short-lived GOOGLE_APPLICATION_CREDENTIALS environment variable'
    required: false
  instance:
    description: 'CloudSQL instance'
    required: true
  port:
    description: 'Listen on port'
    required: false
    default: 5432
  proxy_version:
    description: 'CloudSQL Proxy Version'
    required: false
    default: v2.5.0

runs:
  using: 'composite'
  steps:
    - name: Start Google Cloud SQL Proxy
      shell: bash
      run: |
        # Download Linux binary
        wget -q https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/${{ inputs.proxy_version }}/cloud-sql-proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy

        # Start Cloud SQL Proxy
        ./cloud_sql_proxy ${{ inputs.instance }} --address 0.0.0.0 --port ${{ inputs.port }} --health-check --quitquitquit &

        # Wait until proxy is ready
        isready=1
        for i in {1..10}; do
          echo "Wait for connections to be ready ... $i/10"
          if curl -s -X GET http://localhost:9090/readiness >/dev/null; then
            isready=0
            break
          fi
          sleep 2
        done

        # Exit with error code if we couldn't connect
        exit $isready

        # exit with error code if we couldn't connect
        if [[ $isready -ne 0 ]]; then
          exit $isready
        fi
